# Generated by Django 3.2.6 on 2021-08-08 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.IntegerField(blank=True, default=0, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('image_link', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
