# Generated by Django 3.2.6 on 2021-08-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210808_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Rated'), (1, 'Do Not Read'), (2, 'Very Bad'), (3, 'Bad'), (4, 'Mediocre'), (5, 'So So'), (6, 'Fine'), (7, 'Good'), (8, 'Very Good'), (9, 'Great'), (10, 'Masterwork')], default=1, null=True),
        ),
    ]
