# Generated by Django 3.2.6 on 2021-08-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-review_date']},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='9780345342966', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(choices=[(0, 'Not Rated'), (1, 'Do Not Read'), (2, 'Very Bad'), (3, 'Bad'), (4, 'Mediocre'), (5, 'So So'), (6, 'Fine'), (7, 'Good'), (8, 'Very Good'), (9, 'Great'), (10, 'Masterwork')], default=0),
        ),
    ]
